---
# tasks file for rabbitmq
- name: add the official rabbitmq repository's key
  apt_key: url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: add the official rabbitmq repository
  copy: src=rabbitmq.list dest=/etc/apt/sources.list.d/ backup=yes
  register: aptrepo

- name: refresh apt cache
  apt: update_cache=yes
  when: aptrepo.changed

- name: install rabbitmq-server
  apt: name=rabbitmq-server state=present

- name: create the ssl folder for rabbitmq
  file:
    path=/etc/rabbitmq/ssl/
    owner=rabbitmq
    group=rabbitmq
    mode=0750
    state=directory
  when: rabbitmq_ssl

- name: copy the ssl certificates
  copy:
    src=files/rabbitmq_{{ item }}.pem
    dest=/etc/rabbitmq/ssl/{{ item }}.pem
    owner=rabbitmq
    group=rabbitmq
    mode=0640
    backup=yes
  with_items:
    - "{{ rabbitmq_cacert }}"
    - "{{ rabbitmq_server_key }}"
    - "{{ rabbitmq_server_cert }}"
  when: rabbitmq_ssl

- name: generate the configuration of rabbitmq
  template:
    src=rabbitmq.config.j2
    dest=/etc/rabbitmq/rabbitmq.config
    owner=rabbitmq
    group=rabbitmq
    mode=0644
    backup=yes
  notify: restart rabbitmq-server

- name: enable plugins
  rabbitmq_plugin: names={{ rabbitmq_plugins | join(',') }} state=enabled new_only={{ rabbitmq_new_only }}
  notify: restart rabbitmq-server
  when: rabbitmq_plugins != []

- name: get the list of active plugins to disable
  command: rabbitmq-plugins list -e -m
  register: result
  when: rabbitmq_plugins == []

- name: disable plugins if none added in the configuration
  rabbitmq_plugin: name={{ item }} state=disabled
  notify: restart rabbitmq-server
  with_items: result.stdout_lines
  when: rabbitmq_plugins == []

- name: enable rabbitmq-server to survive reboot
  service: name=rabbitmq-server enabled=yes

- include: vhost.yml

- include: federation.yml
  when: rabbitmq_federation
